### ISSUE TITLE
Latest version 1.7.0 is not compatible with Android Studio Flamingo | 2022.2.1 Patch 2

### ISSUE THREAD

**Issue by UniqueTokens** [jeppeman/GloballyDynamic#106]
Plugin 'GloballyDynamic' (version '1.7.0') is not compatible with the current version of the IDE, because it requires build 221.* or older but the current build is AI-222.4459.24

Android Studio Flamingo | 2022.2.1 Patch 2
Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.3.8-200.fc38.x86_64

**Comment by jeppeman** [comment]
Hey, thanks for reporting. I'll bump during the day.

**Comment by jeppeman** [comment]
@UniqueTokens turns out it was a bit more complicated than a bump.. the latest version of AS introduced some painful breaking changes to for the plugin, it's been sorted and submitted for review now however, should be available within a couple of days. :) I'll keep you posted

**Comment by jeppeman** [comment]
@UniqueTokens alright, version 1.8.0 is now available.

**Comment by UniqueTokens** [comment]
AS Plugin installed, works. Thanks!
