### ISSUE TITLE
Make server lib compatible with gradle 8.0 currently it's on 7.6

### ISSUE THREAD

**Issue by ucdevinda123** [jeppeman/GloballyDynamic#108]
### Description
Build failure due to 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
### Steps to Reproduce
Run ./gradlew executableJar -PoutputDir=$(pwd) -ParchiveName=globallydynamic-server.jar

Build will fail under gradle 8.0

**Comment by jeppeman** [comment]
Hey, thanks for reporting. Fixed now.
