### ISSUE TITLE
deferred uninstall does not work. Is there is any way to uninstall the downloaded feature?

### ISSUE THREAD

**Issue by vaibhavsharma316** [jeppeman/GloballyDynamic#111]

**Comment by jeppeman** [comment]
Hi! If I recall the way Play Feature delivery works correctly: you make a request to uninstall a feature, but it doesn't actually get uninstalled right away, it is sort of marked for deletion to take place at a future point in time when space is needed on the device.

**Comment by vaibhavsharma316** [comment]
I am uploading my bundle on my server instead of Google Play. Is it possible to uninstall it when not using Google Play. I debugged the code and found these are split apks that gets installed. Do you know any way by which I can remove the split apk's once installed.

The split apk resides in the data/app folder. But our application doesn't have access to this folder.

**Comment by jeppeman** [comment]
The library still just defers [SplitInstallManager](https://developer.android.com/reference/com/google/android/play/core/splitinstall/SplitInstallManager) to uninstall split APKs for the self hosted variant as well. I can look into implementing a custom uninstaller, I'll get back to you.

**Comment by jeppeman** [comment]
Looks it is possible to do, there is [this method](https://developer.android.com/reference/android/content/pm/PackageInstaller.Session#removeSplit(java.lang.String)) - I tried it out and it seems to work. Would you like me too add it for the self hosted versiono?

**Comment by vaibhavsharma316** [comment]
It would be great if you can add it in the self hosted version. I had tried this removeSplit method earlier but didn't work me, anyways.  That's fine if it ask for the user confirmation ,I am working on to supress the user confirmation dialog that won't be a issue. 

Thanks a lot for finding the fix

**Comment by jeppeman** [comment]
Ok, great. I'll let you know when it's done. I'll try and find some time during the week.

**Comment by jeppeman** [comment]
Hi, I've published a new version of the android library (`1.3.0`) with support for uninstalling now. See usage example in  [release notes](https://globallydynamic.io/release-notes). You can also see a fully working example in action in the [minimal sample app](https://github.com/jeppeman/GloballyDynamic/tree/master/globallydynamic-android-lib/minimal-sample). Let me know if it works for you.

**Comment by vaibhavsharma316** [comment]
Thanks a lot. I will check and let you know

**Comment by vaibhavsharma316** [comment]
I tried your minimal-sample app but during project build getting an error.

Task 'wrapper' not found in project ':minimal-sample' and it's subprojects

**Comment by jeppeman** [comment]
You need to open the project in android studio from `globallydynamic-android-lib`, then run the `minimal-sample` app module

**Comment by vaibhavsharma316** [comment]
Thanks for the uninstall feature. I can now able to remove installed modules. Able to run minimal sample as well.

**Comment by jeppeman** [comment]
Great, thanks. Closing this then
