### ISSUE TITLE
Support for On Demand Modules?

### ISSUE THREAD

**Issue by rayw-dronesense** [jeppeman/GloballyDynamic#112]
### Description

Google Play Core supports On Demand Modules as part of their "Dynamic delivery" solutions suite.

Does GloballyDynamic already have or plan to have equivalent functionality? https://developer.android.com/guide/playcore/feature-delivery/on-demand

Thanks!

**Comment by jeppeman** [comment]
Hello! Yes, it is supported, you can have a look at the [minimal sample app](https://github.com/jeppeman/GloballyDynamic/tree/master/globallydynamic-android-lib/sample) that performs a dynamic install

**Comment by rayw-dronesense** [comment]
Great, thanks for confirming!
