### ISSUE TITLE
GloballyDynamic not compatible with AGP 8.0.2

### ISSUE THREAD

**Issue by FlavioConrado** [jeppeman/GloballyDynamic#114]
### Description
While trying to update my project to AGP 8.0.2 ('com.android.tools.build:gradle:8.0.2') I saw that I got the following error while trying to build the project: Unable to load class 'com.android.builder.packaging.JarMerger'. If I downgrade it to it's initial version (AGP 7.2.1) the build come back to normal.

### GloballyDynamic gradle plugin version
'com.jeppeman.globallydynamic.gradle:plugin:1.6.0'

### GloballyDynamic android library version
'com.jeppeman.globallydynamic.android:selfhosted:1.3.0'

### GloballyDynamic android studio plugin version
implementation 'com.jeppeman.globallydynamic.android:selfhosted:1.3.0'

### Android Studio Version
Android Studio Flamingo | 2022.2.1 Patch 2

**Comment by FlavioConrado** [comment]
After downloading the globallydynamic gradle plugin, I saw that the class JarMerger is missing on version 8.0.2 of gradle:
![image](https://github.com/jeppeman/GloballyDynamic/assets/135764945/c9bfdbe4-2995-42e8-8fde-7b343dcf1dca)

**Comment by FlavioConrado** [comment]
Found that the JarMerger were moved to JarFlinger.

**Comment by jeppeman** [comment]
Hey @FlavioConrado, thanks for reporting. Will take a look as soon as I have some time to spare; probably tomorrow.

**Comment by FlavioConrado** [comment]
I made some changes that made it work with AGP 8, you could you as base for what need to be changed.

**Comment by FlavioConrado** [comment]
[globally_dynamic_patch.zip](https://github.com/jeppeman/GloballyDynamic/files/12445370/globally_dynamic_patch.zip)

**Comment by jeppeman** [comment]
> [globally_dynamic_patch.zip](https://github.com/jeppeman/GloballyDynamic/files/12445370/globally_dynamic_patch.zip)

Thanks! I've made the changes now, will publish during the day. I'll keep you posted.

**Comment by jeppeman** [comment]
Hey @FlavioConrado, sorry for the wait, but version `1.7.0` of the gradle plugin has been published now.

**Comment by FlavioConrado** [comment]
Thanks @jeppeman!
