### ISSUE TITLE
Latest version 1.9.0 is not compatible with Android Studio Hedgehog | 2023.1.1

### ISSUE THREAD

**Issue by Horribile** [jeppeman/GloballyDynamic#116]
Plugin 'GloballyDynamic' (version '1.9.0') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is AI-231.9392.1

Android Studio Hedgehog | 2023.1.1
Build #AI-231.9392.1.2311.11076708, built on November 9, 2023
Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.2

**Comment by jeppeman** [comment]
Hey, thanks for reporting. I'm on vacation currently but will get to this when I have some time to carve out.

**Comment by jeppeman** [comment]
@Horribile new version (1.10.0) available now
