### ISSUE TITLE
Latest version 1.10.0 is not compatible with Android Studio Koala (Koala Feature Drop | 2024.1.2)

### ISSUE THREAD

**Issue by vhaudiquet** [jeppeman/GloballyDynamic#120]
Hi,

The plugin is not compatible with current version of the IDE

I guess this will happen for you at every IDE update, which might be a bit tedious for you to support.
Maybe this could be automated/semi-automated ?

Anyway, thank you for your awesome work !

**Comment by jeppeman** [comment]
Hi, thanks for reporting. I will upgrade during the weekend, I'll ping you when it is done :)

**Comment by jeppeman** [comment]
I've sent a new version (1.11.0) with Koala support for review now, should be live within a couple of business days

**Comment by jeppeman** [comment]
Hi @vhaudiquet, the new version is live now

**Comment by vhaudiquet** [comment]
Thank you! I just installed it and it seems to work
