### ISSUE TITLE
Unresolved reference: GloballyDynamicBuildConfig

### ISSUE THREAD

**Issue by vhaudiquet** [jeppeman/GloballyDynamic#127]
### Description

I wanted to automatically list all possible dynamic features modules, using this code :
```kotlin
import com.jeppeman.globallydynamic.generated.GloballyDynamicBuildConfig

...

for(feature in GloballyDynamicBuildConfig().onDemandFeatures)
{
    //  The ListItem view for this module
    PluginView(feature)
}
```

However, when building the app (either with build or bundle), I get : 
```
Unresolved reference: generated
Unresolved reference: GloballyDynamicBuildConfig
```

I wonder if the generator is working ? Or did I not initialize it properly ?
I think that by default gradle should generate all the BuildConfig classes properly, but maybe I need a specific setting ?

Or maybe we are not meant to use such a class, and it is only internal ?

### Steps to Reproduce

Try to use `GloballyDynamicBuildConfig` in a project

### GloballyDynamic gradle plugin version

1.8.0

### GloballyDynamic android library version

1.3.0

### GloballyDynamic android studio plugin version

1.11.0

### Android Studio Version

Koala Feature Drop

**Comment by jeppeman** [comment]
Hi, the class is only meant for use internally within the library. But if you want to use it you can explicitly add it to your java sources:

```groovy
android {
   sourceSets {
        main {
            java {
                srcDirs += "${buildDir}/generated/source/globallydynamic/debug"
            }
        }
    }
}
```

**Comment by vhaudiquet** [comment]
For the posterity :

I added this in app gradle configuration, using Kotlin DSL : 
```kotlin
sourceSets.getByName("main") {
        java.setSrcDirs(java.srcDirs.plus("${layout.buildDirectory.get().asFile.path}/generated/source/globallydynamic/debug"))
    }
```

I also had to add an explicit dependency in the project gradle file, using Kotlin DSL : 
```kotlin
tasks.findByPath(":app:compileDebugKotlin")?.dependsOn(":app:writeGloballyDynamicConfigurationSourceFilesForDebug")
```

It all works now ! Thank you
