### ISSUE TITLE
Latest version 1.11.0 is not compatible with Android Studio Ladybug (Android Studio Ladybug | 2024.2.1)

### ISSUE THREAD

**Issue by vhaudiquet** [jeppeman/GloballyDynamic#128]
### Description

Title says everything, same as last time #120 

### GloballyDynamic android studio plugin version

1.11.0

### Android Studio Version

Android Studio Ladybug | 2024.2.1

**Comment by jeppeman** [comment]
Hi, thanks for reporting. I've submitted a new version for review, should be ready early next week.

**Comment by jeppeman** [comment]
The new version should be live now @vhaudiquet

**Comment by vhaudiquet** [comment]
Nice, thank you !
