### ISSUE TITLE
Unable to configure `locallyDynamic` in app/build.gradle.kts

### ISSUE THREAD

**Issue by mochadwi** [jeppeman/GloballyDynamic#20]
### Description
Thanks for this great plugins!

Testing the AAB without hassle with your library.

I have problems with `locallyDynamic` unresolved inside `app/build.gradle.kts`

### LocallyDynamic gradle plugin version
0.2

### LocallyDynamic android library version
0.3

### LocallyDynamic android studio plugin version
0.5

### Android Studio Version
4.0

### Link to a public git repo demonstrating the problem:
(company project)

**Comment by mochadwi** [comment]
@jeppeman

**Comment by jeppeman** [comment]
Hi, this is not due to AGP 4.0, but rather incompatibility with kotlin script; I will have a look at the issue

**Comment by mochadwi** [comment]
apply plugins (using both method): ![Screen Shot 2020-07-01 at 5 58 51 PM](https://user-images.githubusercontent.com/7057959/86236676-ab4a9f80-bbc4-11ea-9e12-63ec7f971a36.png)

configure task: ![Screen Shot 2020-07-01 at 5 58 14 PM](https://user-images.githubusercontent.com/7057959/86236614-940bb200-bbc4-11ea-921f-4914c9e45498.png)

Throw this error: `Extension of type 'LocallyDynamicExtension' does not exist.`

@jeppeman

**Comment by mochadwi** [comment]
Although, I can get rid of the above error with this approach:

```
                    plugins.withId("...locallydynamic...") {
                        configure<com.jeppeman.locallydynamic.gradle.LocallyDynamicExtension> {
                            enabled = true
                            throttleDownloadBy = 200
                        }
                    }
```

But, how to test if the locallydynamic is enabled or not? @jeppeman

**Comment by jeppeman** [comment]
Yes, working on a fix

**Comment by jeppeman** [comment]
This should be fixed, although the new version of the Android Studio plugin needs to be approved by Jetbrains first (version 0.6).

Then use as follows from `build.gradle.kts`:
```kotlin
import com.jeppeman.locallydynamic.gradle.extensions.locallyDynamic

android {   
    buildTypes {
        getByName("debug") {
            locallyDynamic {
                ...
            }
        }
    }
}
```

**Comment by mochadwi** [comment]
Thanks for the fix & updates @jeppeman Will be waiting for the jetbrains to approved your plugins :)

**Comment by jeppeman** [comment]
👍  AS plugin 0.6 is live now
