### ISSUE TITLE
Compatible with Android Studio 4.1

### ISSUE THREAD

**Issue by Omico** [jeppeman/GloballyDynamic#36]
### Description
In this [commit](https://android.googlesource.com/platform/tools/adt/idea/+/79cd75c8f4011e47e14ef269f0b97036c2baa8e0), they remove ModuleSetupStep.java that causing the project to report an error in this [file](https://github.com/jeppeman/GloballyDynamic/blob/master/globallydynamic-studio-plugin/src/main/kotlin/com/jeppeman/globallydynamic/idea/PostModuleSyncStep.kt).

I don't have any experience in writing a Gradle plugin. So, I can only locate this problem.

PS:
intellij.version '201.8743.12'
gradle version 6.5

### GloballyDynamic android studio plugin version
1.0
### Android Studio Version
4.1.0

**Comment by jeppeman** [comment]
Thanks, I'll make a fix tomorrow

**Comment by jeppeman** [comment]
New release available
