### ISSUE TITLE
This resource still maintain in the future? 

### ISSUE THREAD

**Issue by AnhDTN** [jeppeman/GloballyDynamic#45]
Hi, 
I seen this plugin, and it very great for me. Thank you and thank your team so much <3 
I will develop application but it will not upload to google play because it violate  policy google. Therefore I want to confirm that you will continue to maintain this plugin or not?

**Comment by jeppeman** [comment]
Hello,

Glad it has been helpful. Yes, I will continue maintaining it.

/Jesper

**Comment by AnhDTN** [comment]
> maintaining

Thank you so much ^^. This is great. I will close issue. To day is a beautiful day with me <3
