### ISSUE TITLE
Plugin broken on latest version of android studio (bumblebee)

### ISSUE THREAD

**Issue by dranzerashi** [jeppeman/GloballyDynamic#69]
### Description
Plugin broken on latest version of android studio (bumblebee)
### GloballyDynamic android studio plugin version
1.3.0
### Android Studio Version
Android Studio Bumblebee | 2021.1.1
Build #AI-211.7628.21.2111.8092744, built on January 19, 2022

**Comment by jeppeman** [comment]
Hey, thanks for the rport @dranzerashi, I'll get to it during the week.

**Comment by jeppeman** [comment]
Version 1.4.0 is now available in AS.
