### ISSUE TITLE
User guide link is broken

### ISSUE THREAD

**Issue by fnzainal** [jeppeman/GloballyDynamic#85]
### Description
the [user guide's](https://globallydynamic.io/user-guide)  link return blank empty page.

### Steps to Reproduce
just click the link https://globallydynamic.io/user-guide

Please fix it, this repo looks interest for me.

**Comment by jeppeman** [comment]
Thanks for the report! I'm on vacation so can't fix it for a couple of weeks. In the meantime you can go to https://globallydynamic.io/ and just navigate from there.

**Comment by jeppeman** [comment]
@fnzainal this should be fixed now
