### ISSUE TITLE
How to Increase Timeout Seconds

### ISSUE THREAD

**Issue by teleazmeer** [jeppeman/GloballyDynamic#86]

**Comment by jeppeman** [comment]
@teleazmeer what timeout are you referring to?

**Comment by teleazmeer** [comment]
The Read and connect timeout for httpclient inside 
globallydynamic-selfhosted\src\main\java\com\jeppeman\globallydynamic\globalsplitinstall\GlobalSplitInstallManagerImpl.java

Line 61 
when i request for split apk from s3 it gives timeout error. so need to increase them

**Comment by jeppeman** [comment]
Gotcha, right, they are not modifiable at the moment. I will get started on introducing the capability to customize them, should be done today or tomorrow. I'll let you know when there is a new version!

**Comment by teleazmeer** [comment]
Thats Great to Hear ,,... Thanks a Lot....

**Comment by jeppeman** [comment]
@teleazmeer support for this has been added now.

```gradle
android {
    globallyDynamicServers {
        myServer {
            downloadConnectTimeout 15000
            downloadReadTimeout 120000
        }
    }
}
```

See docs here: https://globallydynamic.io/docs/user/gradle

Android lib version: 1.2.0
Gradle plugin version: 1.5.0

**Comment by teleazmeer** [comment]
Thank YOu
