### ISSUE TITLE
How Do We Uninstall Modules

### ISSUE THREAD

**Issue by teleazmeer** [jeppeman/GloballyDynamic#90]
How to Uninstall Dynamic Features @jeppeman

**Comment by jeppeman** [comment]
@teleazmeer `GlobalSplitInstallManager#deferredUninstall()`. Note that modules don't get uninstalled instantaneously though, they will eventually get removed in the background.
See here for more details: https://developer.android.com/reference/com/google/android/play/core/splitinstall/SplitInstallManager#deferredUninstall(java.util.List%3Cjava.lang.String%3E)
